# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# - TST: ssh lvlds@177.126.188.182
# - DEV: ssh -p 10022 lvlds@177.126.188.211
# - HOM: ssh -p 10022 lvlds@177.126.188.223
# - PROD: ssh -p 10022 lvlds@200.143.189.253

# On nginx node open tunnel with febrafar prometheus instance
# ssh -f -N -L 9091:127.0.0.1:9090 -i /opt/devops/.ssh/id_rsa_operator lvlds@177.126.188.182

# ssh -f -N -L 9101:127.0.0.1:9100 lvlds@177.126.188.211
# ssh -f -N -L 9102:127.0.0.1:9100 lvlds@177.126.188.223
# ssh -f -N -L 9103:127.0.0.1:9100 lvlds@200.143.189.253

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']
  - job_name: 'node_febrafar_tst'
    static_configs:
      - targets: ['127.0.0.1:9100']
  - job_name: 'node_febrafar_dev'
    static_configs:
      - targets: ['127.0.0.1:9101']
  - job_name: 'node_febrafar_hom'
    static_configs:
      - targets: ['127.0.0.1:9102']
  - job_name: 'node_febrafar_prod'
    static_configs:
      - targets: ['127.0.0.1:9103']