# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']
  - job_name: 'node_nginx'
    static_configs:
      - targets: ['127.0.0.1:9100']
  - job_name: 'node_brux0795'
    static_configs:
      - targets: ['127.0.0.1:9101']
  - job_name: 'node_brux0794'
    static_configs:
      - targets: ['127.0.0.1:9102']
  - job_name: 'node_brux0796'
    static_configs:
      - targets: ['127.0.0.1:9103']
  - job_name: 'node_brux0793'
    static_configs:
      - targets: ['127.0.0.1:9104']
  - job_name: 'process_nginx'
    static_configs:
      - targets: ['127.0.0.1:9256']
  - job_name: 'ngin_elasticsearch'
    scrape_interval: 15s
    metrics_path: "/_prometheus/metrics"
    static_configs:
    - targets:
      - 127.0.0.1:9200
